version: "3.7"

services:
  meetup-events: 
    image: paulopez/meetup-events:2.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MeetupEvents: "Host=database;Port=5432;Database=meetupevents;Username=postgres;Password=mysecretpassword"
    ports:
      - 5000:80

  database:
    image: postgres
    environment:
     POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data