version: "3.7"

services:
  database:
    image: postgres
    environment:
     POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      
  rabbitmq:
    container_name: rabbitmq
    build: 
      context: ./rabbitmq
    image: rabbitmq-plugins
    ports:
      - "15672:15672"
      - "5672:5672"
  
networks:
  default:
    name: meetup-network
  